#ifndef HIS_DOMAIN_DOMAIN_TYPES_H
#define HIS_DOMAIN_DOMAIN_TYPES_H

#define HIS_DOMAIN_ID_CAPACITY 16
#define HIS_DOMAIN_NAME_CAPACITY 64
#define HIS_DOMAIN_TITLE_CAPACITY 64
#define HIS_DOMAIN_LOCATION_CAPACITY 64
#define HIS_DOMAIN_TEXT_CAPACITY 128
#define HIS_DOMAIN_LARGE_TEXT_CAPACITY 256
#define HIS_DOMAIN_TIME_CAPACITY 32
#define HIS_DOMAIN_CONTACT_CAPACITY 32

#endif
