# CMake generated Testfile for 
# Source directory: /Users/cornna/project/his/his
# Build directory: /Users/cornna/project/his/his/build-win64
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_result]=] "/Users/cornna/project/his/his/build-win64/test_result.exe")
set_tests_properties([=[test_result]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;106;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_common]=] "/Users/cornna/project/his/his/build-win64/test_common.exe")
set_tests_properties([=[test_common]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;114;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_domain]=] "/Users/cornna/project/his/his/build-win64/test_domain.exe")
set_tests_properties([=[test_domain]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;122;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_repository_utils]=] "/Users/cornna/project/his/his/build-win64/test_repository_utils.exe")
set_tests_properties([=[test_repository_utils]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;130;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_patient_repository]=] "/Users/cornna/project/his/his/build-win64/test_patient_repository.exe")
set_tests_properties([=[test_patient_repository]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;138;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_doctor_repository]=] "/Users/cornna/project/his/his/build-win64/test_doctor_repository.exe")
set_tests_properties([=[test_doctor_repository]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;146;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_registration_repository]=] "/Users/cornna/project/his/his/build-win64/test_registration_repository.exe")
set_tests_properties([=[test_registration_repository]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;154;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_doctor_service]=] "/Users/cornna/project/his/his/build-win64/test_doctor_service.exe")
set_tests_properties([=[test_doctor_service]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;163;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_registration_service]=] "/Users/cornna/project/his/his/build-win64/test_registration_service.exe")
set_tests_properties([=[test_registration_service]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;171;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_patient_service]=] "/Users/cornna/project/his/his/build-win64/test_patient_service.exe")
set_tests_properties([=[test_patient_service]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;179;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_pharmacy_service]=] "/Users/cornna/project/his/his/build-win64/test_pharmacy_service.exe")
set_tests_properties([=[test_pharmacy_service]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;187;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_inpatient_domain]=] "/Users/cornna/project/his/his/build-win64/test_inpatient_domain.exe")
set_tests_properties([=[test_inpatient_domain]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;195;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_bed_service]=] "/Users/cornna/project/his/his/build-win64/test_bed_service.exe")
set_tests_properties([=[test_bed_service]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;203;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_inpatient_service]=] "/Users/cornna/project/his/his/build-win64/test_inpatient_service.exe")
set_tests_properties([=[test_inpatient_service]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;211;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_medical_record_service]=] "/Users/cornna/project/his/his/build-win64/test_medical_record_service.exe")
set_tests_properties([=[test_medical_record_service]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;219;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_menu_controller]=] "/Users/cornna/project/his/his/build-win64/test_menu_controller.exe")
set_tests_properties([=[test_menu_controller]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;227;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_menu_application]=] "/Users/cornna/project/his/his/build-win64/test_menu_application.exe")
set_tests_properties([=[test_menu_application]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;235;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_desktop_state]=] "/Users/cornna/project/his/his/build-win64/test_desktop_state.exe")
set_tests_properties([=[test_desktop_state]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;243;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_desktop_adapters]=] "/Users/cornna/project/his/his/build-win64/test_desktop_adapters.exe")
set_tests_properties([=[test_desktop_adapters]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;251;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_desktop_workflows]=] "/Users/cornna/project/his/his/build-win64/test_desktop_workflows.exe")
set_tests_properties([=[test_desktop_workflows]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;259;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_desktop_layout_rules]=] "/Users/cornna/project/his/his/build-win64/test_desktop_layout_rules.exe")
set_tests_properties([=[test_desktop_layout_rules]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;267;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_patient_workbench_flow]=] "/Users/cornna/project/his/his/build-win64/test_patient_workbench_flow.exe")
set_tests_properties([=[test_patient_workbench_flow]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;275;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_doctor_workbench_flow]=] "/Users/cornna/project/his/his/build-win64/test_doctor_workbench_flow.exe")
set_tests_properties([=[test_doctor_workbench_flow]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;283;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_inpatient_ward_workbench_flow]=] "/Users/cornna/project/his/his/build-win64/test_inpatient_ward_workbench_flow.exe")
set_tests_properties([=[test_inpatient_ward_workbench_flow]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;291;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_pharmacy_admin_workbench_flow]=] "/Users/cornna/project/his/his/build-win64/test_pharmacy_admin_workbench_flow.exe")
set_tests_properties([=[test_pharmacy_admin_workbench_flow]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;299;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_admin_workbench_support]=] "/Users/cornna/project/his/his/build-win64/test_admin_workbench_support.exe")
set_tests_properties([=[test_admin_workbench_support]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;307;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_demo_data_integrity]=] "/Users/cornna/project/his/his/build-win64/test_demo_data_integrity.exe")
set_tests_properties([=[test_demo_data_integrity]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;315;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
add_test([=[test_auth_service]=] "/Users/cornna/project/his/his/build-win64/test_auth_service.exe")
set_tests_properties([=[test_auth_service]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/cornna/project/his/his/CMakeLists.txt;323;add_test;/Users/cornna/project/his/his/CMakeLists.txt;0;")
subdirs("third_party/raylib_vendor")
