#!/usr/bin/env python3

import argparse
import ast
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src/ui/DesktopGlyphSeed.h"
SOURCE_PATTERNS = (
    "src/ui/DesktopApp.c",
    "src/ui/DesktopPages.c",
    "src/ui/DesktopAdapters.c",
    "src/ui/WorkbenchCommon.c",
    "src/ui/workbench/*.c",
    "include/ui/Desktop*.h",
    "include/ui/Workbench*.h",
    "data/*.txt",
)
STRING_LITERAL_RE = re.compile(r'"([^"\\]*(?:\\.[^"\\]*)*)"')


def iter_source_files():
    seen = set()
    for pattern in SOURCE_PATTERNS:
        for path in sorted(ROOT.glob(pattern)):
            resolved = path.resolve()
            if resolved in seen or not path.is_file():
                continue
            seen.add(resolved)
            yield path


def decode_c_string(value: str) -> str:
    return ast.literal_eval(f'"{value}"')


def collect_glyphs() -> str:
    chars = set()

    for path in iter_source_files():
        text = path.read_text(encoding="utf-8")
        if path.suffix in {".c", ".h"}:
            for literal in STRING_LITERAL_RE.findall(text):
                decoded = decode_c_string(literal)
                for char in decoded:
                    if ord(char) > 126:
                        chars.add(char)
        else:
            for char in text:
                if ord(char) > 126:
                    chars.add(char)

    return "".join(sorted(chars))


def render_header(seed: str) -> str:
    chunks = [seed[index:index + 60] for index in range(0, len(seed), 60)]
    lines = [
        "#ifndef HIS_UI_DESKTOP_GLYPH_SEED_H",
        "#define HIS_UI_DESKTOP_GLYPH_SEED_H",
        "",
        "/* Auto-generated by scripts/sync-desktop-glyph-seed.py. */",
        "#define HIS_DESKTOP_GLYPH_SEED_TEXT \\",
    ]

    for index, chunk in enumerate(chunks):
        suffix = " \\" if index != len(chunks) - 1 else ""
        lines.append(f'    "{chunk}"{suffix}')

    lines.extend(["", "#endif"])
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    seed = collect_glyphs()
    rendered = render_header(seed)

    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
        return 0

    if args.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing != rendered:
            sys.stderr.write("Desktop glyph seed is out of date. Run scripts/sync-desktop-glyph-seed.py --write\n")
            return 1
        return 0

    sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
